In [1]:
import numpy as np
import csv
from Scripts.getdata import data,header

[['1' '0' '3' ..., '7.25' '' 'S']
 ['2' '1' '1' ..., '71.2833' 'C85' 'C']
 ['3' '1' '3' ..., '7.925' '' 'S']
 ..., 
 ['889' '0' '3' ..., '23.45' '' 'S']
 ['890' '1' '1' ..., '30' 'C148' 'C']
 ['891' '0' '3' ..., '7.75' '' 'Q']]


In [2]:
print data[0]
print data[-1]
print header

['1' '0' '3' 'Braund, Mr. Owen Harris' 'male' '22' '1' '0' 'A/5 21171'
 '7.25' '' 'S']
['891' '0' '3' 'Dooley, Mr. Patrick' 'male' '32' '0' '0' '370376' '7.75' ''
 'Q']
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']


In [3]:
#print data[0::,2].astype(np.float)
print type(data[0::,2]) 
print data[0::,2]

<type 'numpy.ndarray'>
['3' '1' '3' '1' '3' '3' '1' '3' '3' '2' '3' '1' '3' '3' '3' '2' '3' '2'
 '3' '3' '2' '2' '3' '1' '3' '3' '3' '1' '3' '3' '1' '1' '3' '2' '1' '1'
 '3' '3' '3' '3' '3' '2' '3' '2' '3' '3' '3' '3' '3' '3' '3' '3' '1' '2'
 '1' '1' '2' '3' '2' '3' '3' '1' '1' '3' '1' '3' '2' '3' '3' '3' '2' '3'
 '2' '3' '3' '3' '3' '3' '2' '3' '3' '3' '3' '1' '2' '3' '3' '3' '1' '3'
 '3' '3' '1' '3' '3' '3' '1' '1' '2' '2' '3' '3' '1' '3' '3' '3' '3' '3'
 '3' '3' '1' '3' '3' '3' '3' '3' '3' '2' '1' '3' '2' '3' '2' '2' '1' '3'
 '3' '3' '3' '3' '3' '3' '3' '2' '2' '2' '1' '1' '3' '1' '3' '3' '3' '3'
 '2' '2' '3' '3' '2' '2' '2' '1' '3' '3' '3' '1' '3' '3' '3' '3' '3' '2'
 '3' '3' '3' '3' '1' '3' '1' '3' '1' '3' '3' '3' '1' '3' '3' '1' '2' '3'
 '3' '2' '3' '2' '3' '1' '3' '1' '3' '3' '2' '2' '3' '2' '1' '1' '3' '3'
 '3' '2' '3' '3' '3' '3' '3' '3' '3' '3' '3' '1' '3' '2' '3' '2' '3' '1'
 '3' '2' '1' '2' '3' '2' '3' '3' '1' '3' '2' '3' '2' '3' '1' '3' '2' '3'
 '2' '3' '2' '2' '2' '2' '3'

In [4]:
num_passengers=np.size(data[0::,1].astype(np.float))
print num_passengers
bool_idx = data[0::,1].astype(np.float)>0
#print bool_idx
num_survivors=np.size(data[0::,1][bool_idx])
print num_survivors

891
342


In [5]:
proportion_survivors = num_survivors/num_passengers

In [6]:
women_rows = data[:,4] == "female"
men_rows = data[:,4] != "female"

In [7]:
proportion_women_survived = np.sum(data[women_rows,1].astype(float))/np.size(data[women_rows,1])
proportion_men_survived = np.sum(data[men_rows,1].astype(float))/np.size(data[men_rows,1])

print proportion_women_survived
print proportion_men_survived

0.742038216561
0.188908145581


In [8]:
testfile = open("../csv/test.csv","rb")
test_file_object = csv.reader(testfile)
header_test = test_file_object.next()

data_test = list(test_file_object)
data_test = np.array(data_test)

print data_test

[['892' '3' 'Kelly, Mr. James' ..., '7.8292' '' 'Q']
 ['893' '3' 'Wilkes, Mrs. James (Ellen Needs)' ..., '7' '' 'S']
 ['894' '2' 'Myles, Mr. Thomas Francis' ..., '9.6875' '' 'Q']
 ..., 
 ['1307' '3' 'Saether, Mr. Simon Sivertsen' ..., '7.25' '' 'S']
 ['1308' '3' 'Ware, Mr. Frederick' ..., '8.05' '' 'S']
 ['1309' '3' 'Peter, Master. Michael J' ..., '22.3583' '' 'C']]


In [9]:
outputfile = open("../Predictions/genderbasedmodel.csv","wb")
output_file_object = csv.writer(outputfile)

print header_test

['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']


In [10]:
output_file_object.writerow(["PassengerId","Survived"])
for row in data_test:
    if(row[3]=="female"):
        output_file_object.writerow([row[0],1])
    else:
        output_file_object.writerow([row[0],0])

In [11]:
testfile.close()
outputfile.close()


In [33]:
# Add Ceiling

fare_ceiling = 40
data[ data[:,9].astype(np.float)> fare_ceiling, 9 ] = fare_ceiling -1
#print data[:,9]

In [13]:
fare_bracket = 10
num_brackets = fare_ceiling/fare_bracket
print num_brackets

4


In [14]:
#num_classes = 3
num_classes =  len(np.unique(data[:,2]))
print num_classes

num_genders = len(np.unique(data[:,4]))
print num_genders

3
2


In [15]:
survival_table = np.zeros((num_genders,num_classes,num_brackets))
print survival_table

[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]


In [30]:
for i in xrange(num_classes):
    for j in xrange(num_brackets):
        
        bool_idx_w = (data[:,4] == "female") &\
        (data[:,2].astype(np.float)==i+1) &\
        (data[:,9].astype(np.float)>=j*fare_bracket) &\
        (data[:,9].astype(np.float)<(j+1)*fare_bracket)
                
        bool_idx_m = (data[:,4] == "male") &\
        (data[:,2].astype(np.float)==i+1) &\
        (data[0::,9].astype(np.float)>=j*fare_bracket) &\
        (data[0::,9].astype(np.float)<(j+1)*fare_bracket)
                
        survival_table[0,i,j] = np.mean(data[bool_idx_w,1].astype(np.float))
        survival_table[1,i,j] = np.mean(data[bool_idx_m,1].astype(np.float))
        
survival_table[survival_table!=survival_table] = 0
print survival_table

[[[ 0.          0.          0.83333333  0.97727273]
  [ 0.          0.91428571  0.9         1.        ]
  [ 0.59375     0.58139535  0.33333333  0.125     ]]

 [[ 0.          0.          0.4         0.38372093]
  [ 0.          0.15873016  0.16        0.21428571]
  [ 0.11153846  0.23684211  0.125       0.24      ]]]


In [32]:
survival_table[survival_table>=0.5]=1
survival_table[survival_table<0.5]=0
print survival_table

[[[ 0.  0.  1.  1.]
  [ 0.  1.  1.  1.]
  [ 1.  1.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]


In [38]:
"""
testfile = open("../csv/test.csv","rb")
test_file_object = csv.reader(testfile)
header_test = test_file_object.next()

data_test = list(test_file_object)
data_test = np.array(data_test)

print data_test
"""

outputfile = open("../Predictions/genderclassmodel.csv","wb")
output_file_object = csv.writer(outputfile)

output_file_object.writerow(["PassengerId","Survived"])

for row in data_test:
    
    fare_bin = -1
        
    try:
        row[8] = float(row[8])
    except:
        fare_bin = 3 - float(row[1])
        
    if(row[8]>=fare_ceiling):
        fare_bin = 3
    
    if(fare_bin==-1):
        for j in num_brackets:
            if(row[8]>=j*num_brackets & row[8]<(j+1)*num_brackets):
                fare_bin = j
                break
                
    if(row[3]=="female"):
        output_file_object.writerow([row[0],int(survival_table[0,int(row[1])-1,fare_bin])])
    else:
        output_file_object.writerow([row[0],int(survival_table[1,int(row[1])-1,fare_bin])])
        